name: CI Pull Request

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    uses: ./build.yaml

  lint:
    needs: build
    uses: ./lint.yaml

  test:
    needs: build
    uses: ./test.yaml
