name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sunbright-technologies/bugsies_dev_${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pytest
        run: |
          pytest -v .
