name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sunbright-technologies/bugsies_dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run pytest
        run: |
          pytest -v .
